import { Inter } from 'next/font/google'
import './globals.css'
import Context from './context/context'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'kasir 65',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="  text-blue-300 bg-background dark">  
      <Context >
      <body className={inter.className}>
        <div>
          {children}
          {/* <Navbar /> */}
        </div>
        </body>
      </Context>
    </html>
  )
}
