import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import Context from './context/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'kasir 65',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Context >
      <body className={inter.className}>
        {children}
        {/* <Navbar /> */}
      </body>
      </Context>
    </html>
  )
}
